In [1]:
!pip install h5py

In [2]:
import sys
import os
import shutil
import gzip
import csv
import multiprocessing

import tqdm
import h5py

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
import boda
from boda.common import constants, utils

import matplotlib.pyplot as plt
from scipy.stats import pearsonr, spearmanr

In [3]:
boda_src = os.path.join( os.path.dirname( os.path.dirname( os.getcwd() ) ), 'src' )
sys.path.insert(0, boda_src)

from main import unpack_artifact, model_fn

In [4]:
torch.cuda.device_count()

1

In [5]:
!wget -O - https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz | gunzip -c > GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta


--2022-12-24 20:14:12--  https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
Resolving www.encodeproject.org (www.encodeproject.org)... 34.211.244.144
Connecting to www.encodeproject.org (www.encodeproject.org)|34.211.244.144|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://encode-public.s3.amazonaws.com/2015/12/03/a7fea375-057d-4cdc-8ccd-0b0f930823df/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz?response-content-disposition=attachment%3B%20filename%3DGRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz&AWSAccessKeyId=ASIATGZNGCNXWFDOADEV&Signature=fU%2BH3bqjQXweKAQm5uZP4xZu6eQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEKT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLXdlc3QtMiJHMEUCIFW0%2BjFB40in9rfCOEmZPQn14qxqlyUsu1vFnGIi3qTVAiEAg2oGeVm%2Bojiq%2FxJo%2FIz9GCKmEKNxHA%2BVPDYwJAo1y48q1QQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwyMjA3NDg3MTQ4NjMiDBt%2B4

In [6]:
fasta_fn = 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta' # Genome reference
hpo_rec = 'gs://syrgoth/aip_ui_test/model_artifacts__20211113_021200__287348.tar.gz'

In [7]:
class FlankBuilder(nn.Module):
    def __init__(self,
                 left_flank=None,
                 right_flank=None,
                 batch_dim=0,
                 cat_axis=-1
                ):
        
        super().__init__()
        
        self.register_buffer('left_flank', left_flank.detach().clone())
        self.register_buffer('right_flank', right_flank.detach().clone())
        
        self.batch_dim = batch_dim
        self.cat_axis  = cat_axis
        
    def add_flanks(self, my_sample):
        *batch_dims, channels, length = my_sample.shape
        
        pieces = []
        
        if self.left_flank is not None:
            pieces.append( self.left_flank.expand(*batch_dims, -1, -1) )
            
        pieces.append( my_sample )
        
        if self.right_flank is not None:
            pieces.append( self.right_flank.expand(*batch_dims, -1, -1) )
            
        return torch.cat( pieces, axis=self.cat_axis )
    
    def forward(self, my_sample):
        return self.add_flanks(my_sample)


In [8]:
if os.path.isdir('./artifacts'):
    shutil.rmtree('./artifacts')

unpack_artifact(hpo_rec)

model_dir = './artifacts'

my_model = model_fn(model_dir)
my_model.cuda()
my_model.eval()

archive unpacked in ./


Loaded model from 20211113_021200 in eval mode


BassetBranched(
  (pad1): ConstantPad1d(padding=(9, 9), value=0.0)
  (conv1): Conv1dNorm(
    (conv): Conv1d(4, 300, kernel_size=(19,), stride=(1,))
    (bn_layer): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (pad2): ConstantPad1d(padding=(5, 5), value=0.0)
  (conv2): Conv1dNorm(
    (conv): Conv1d(300, 200, kernel_size=(11,), stride=(1,))
    (bn_layer): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (pad3): ConstantPad1d(padding=(3, 3), value=0.0)
  (conv3): Conv1dNorm(
    (conv): Conv1d(200, 200, kernel_size=(7,), stride=(1,))
    (bn_layer): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (pad4): ConstantPad1d(padding=(1, 1), value=0.0)
  (maxpool_3): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (maxpool_4): MaxPool1d(kernel_size=4, stride=4, padding=0, dilation=1, ceil_mode=False)
  (linear1): LinearNorm(
    (linear): Linear(in

In [9]:
left_flank = boda.common.utils.dna2tensor( 
    boda.common.constants.MPRA_UPSTREAM[-200:] 
).unsqueeze(0)
left_flank.shape

right_flank= boda.common.utils.dna2tensor( 
    boda.common.constants.MPRA_DOWNSTREAM[:200] 
).unsqueeze(0)
right_flank.shape

flank_builder = FlankBuilder(
    left_flank=left_flank,
    right_flank=right_flank,
)

In [10]:
fasta_dict = boda.data.Fasta(fasta_fn)


pre-reading fasta into memory
100%|██████████| 44284892/44284892 [00:17<00:00, 2559516.01it/s]
finding keys
parsing
100%|██████████| 195/195 [08:48<00:00,  2.71s/it] 
done


In [11]:
class Mutagen(nn.Module):
    def __init__(self, seq_len, alphabet=constants.STANDARD_NT):
        super().__init__()
        
        I = torch.eye(seq_len).unsqueeze(1)
        Z = torch.zeros_like(I)
        
        self.seq_len = seq_len
        self.n_tokens = len(alphabet)
        self.register_buffer(
            'clear_positions', 
            (1 - I).expand(-1,self.n_tokens,-1)
        )
        
        for i in range(self.n_tokens):
            self.register_buffer(
                f'set_token_{i}', 
                torch.cat(
                    [ I if i == j else Z for j in range(self.n_tokens) ], 
                    dim=1
                )
            )
        
    def forward(self, input_seq):
        seq_len = input_seq.shape[-1]
        
        if len(input_seq.shape) == 2:
            hook = input_seq.unsqueeze(0).expand(seq_len,-1,-1)
        elif len(input_seq.shape) == 3:
            hook = input_seq.unsqueeze(1).expand(-1,seq_len,-1,-1)
        
        hook = hook * self.clear_positions
        hook = torch.stack(
            [hook + getattr(self, f'set_token_{i}') for i in range(self.n_tokens)],
            dim=0
        )
        
        if len(input_seq.shape) == 3:
            hook = hook.transpose(1,0)
            
        hook = hook.flatten(0,-3)
        
        return hook

In [12]:
class Mutagenizer(nn.Module):
    def __init__(self, seq_len, alphabet=constants.STANDARD_NT):
        super().__init__()
        
        self.n_tokens = len(alphabet)
        
        clear_midpoint = torch.ones((self.n_tokens, self.n_tokens, seq_len*2-1))
        clear_midpoint[:,:,seq_len-1] = 0
        set_variants   = torch.zeros_like(clear_midpoint)
        set_variants[:,:,seq_len-1] = torch.eye(self.n_tokens)
        
        self.register_buffer('clear_midpoint', clear_midpoint)
        self.register_buffer('set_variants', set_variants)
        
        self.windower = boda.data.fasta_datamodule.OneHotSlicer(self.n_tokens,seq_len)
        
    def forward(self, input):
        
        hook = input.unsqueeze(-3)
        shape = list(hook.shape)
        shape[-3] = shape[-2]
        hook = hook.expand(*shape)
        hook = hook * self.clear_midpoint
        hook = hook + self.set_variants
        
        return self.windower( hook.flatten(0,-3) )
        
        


In [13]:
from functools import partial

import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import (random_split, DataLoader, TensorDataset, ConcatDataset)

from torch.distributions.categorical import Categorical

In [14]:
class mpra_predictor(nn.Module):
    def __init__(self,
                 model,
                 pred_idx=0,
                 ini_in_len=200,
                 model_in_len=600,
                 cat_axis=-1,
                 dual_pred=False):
        super().__init__()
        self.model = model
        self.pred_idx = pred_idx
        self.ini_in_len = ini_in_len 
        self.model_in_len = model_in_len
        self.cat_axis = cat_axis  
        self.dual_pred = dual_pred
        
        try: self.model.eval()
        except: pass
        
        self.register_flanks()
    
    def forward(self, x):
        pieces = [self.left_flank.repeat(x.shape[0], 1, 1), x, self.right_flank.repeat(x.shape[0], 1, 1)]
        in_tensor = torch.cat( pieces, axis=self.cat_axis)
        if self.dual_pred:
            dual_tensor = utils.reverse_complement_onehot(in_tensor)
            out_tensor = self.model(in_tensor)[:, self.pred_idx] + self.model(dual_tensor)[:, self.pred_idx]
            out_tensor = out_tensor / 2.0
        else:
            out_tensor = self.model(in_tensor)[:, self.pred_idx]
        return out_tensor
    
    def register_flanks(self):
        missing_len = self.model_in_len - self.ini_in_len
        left_idx = - missing_len//2 + missing_len%2
        right_idx = missing_len//2 + missing_len%2
        left_flank = utils.dna2tensor(constants.MPRA_UPSTREAM[left_idx:]).unsqueeze(0)
        right_flank = utils.dna2tensor(constants.MPRA_DOWNSTREAM[:right_idx]).unsqueeze(0)         
        self.register_buffer('left_flank', left_flank)
        self.register_buffer('right_flank', right_flank) 
        

def isg_contributions(sequences,
                      predictor,
                      num_steps=50,
                      num_samples=20,
                      eval_batch_size=1024,
                      theta_factor=15):
    
    batch_size = eval_batch_size // num_samples
    temp_dataset = TensorDataset(sequences)
    temp_dataloader = DataLoader(temp_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    all_salient_maps = []
    all_gradients = []
    for local_batch in temp_dataloader:
        target_thetas = (theta_factor * local_batch[0].cuda()).requires_grad_()
        line_gradients = []
        for i in range(0, num_steps + 1):
            point_thetas = (i / num_steps * target_thetas)
            point_distributions = F.softmax(point_thetas, dim=-2)

            nucleotide_probs = Categorical(torch.transpose(point_distributions, -2, -1))
            sampled_idxs = nucleotide_probs.sample((num_samples, ))
            sampled_nucleotides_T = F.one_hot(sampled_idxs, num_classes=4)
            sampled_nucleotides = torch.transpose(sampled_nucleotides_T, -2, -1)
            distribution_repeater = point_distributions.repeat(num_samples, *[1 for i in range(3)])
            sampled_nucleotides = sampled_nucleotides - distribution_repeater.detach() + distribution_repeater 
            samples = sampled_nucleotides.flatten(0,1)

            preds = predictor(samples)
            point_predictions = preds.unflatten(0, (num_samples, target_thetas.shape[0])).mean(dim=0)
            point_gradients = torch.autograd.grad(point_predictions.sum(), inputs=point_thetas, retain_graph=True)[0]
            line_gradients.append(point_gradients)
            
        gradients = torch.stack(line_gradients).mean(dim=0).detach()
        all_salient_maps.append(gradients * target_thetas.detach())
        all_gradients.append(gradients)
    return theta_factor * torch.cat(all_gradients).cpu()
    # return torch.cat(all_salient_maps).cpu(), theta_factor * torch.cat(all_gradients).cpu()


def batch_to_contributions(onehot_sequences,
                           model,
                           model_output_len=3,
                           seq_len = 200,
                           eval_batch_size=1040):
    
    extended_contributions = []
    for i in range(model_output_len):
        predictor = mpra_predictor(model=model, pred_idx=i, ini_in_len=seq_len).cuda()
        extended_contributions.append(isg_contributions(onehot_sequences, predictor, eval_batch_size=eval_batch_size))
        
    return torch.stack(extended_contributions, dim=-1)

In [15]:
def prepare_hdf5_file(fa_dataset, h5_file):
    strands = 2 if fa_dataset.reverse_complements else 1
    
    h5_file.create_dataset('contribution_scores', (len(fa_dataset), 4, 200, 3), dtype=np.float16)
    h5_file.create_dataset('locations', (len(fa_dataset), 4), dtype=np.int64)
    
    h5_file['contribution_scores'].attrs['axis_names'] = ['windows', 'tokens', 'length', 'cells']
    h5_file['locations'].attrs['column_names'] = ['contig', 'start', 'end', 'strand']
    h5_file['locations'].attrs['contig_keys'] = fa_dataset.idx2key
    
    h5_file['contribution_scores'].set_fill_value = np.nan
        
    return h5_file


In [43]:
np.arange(1024)[basket[1].sum(dim=[-2,-1]) > 0].size

480

In [45]:
basket[1].shape

torch.Size([1024, 4, 200])

In [48]:
basket[1][np.arange(0,1)].shape

torch.Size([1, 4, 200])

# Run Contribution scores

In [65]:
%%time

seq_len = 200

fasta_data = boda.data.FastaDataset(fasta_dict.fasta, 
                                    window_size=seq_len, step_size=50, 
                                    reverse_complements=False)

fasta_loader = torch.utils.data.DataLoader(fasta_data, batch_size=14, shuffle=False)

f = h5py.File('test_write.hdf5','w')
f = prepare_hdf5_file(fasta_data, f)

mutagenizer = Mutagenizer(seq_len)

h5_start = 0

for i, x in enumerate(tqdm.tqdm(fasta_loader)):
    if i >= 100:
        f.close()
        break

    location, sequence = x

    results = batch_to_contributions(sequence, my_model, model_output_len=3, seq_len = 200, eval_batch_size=1040)

    f['locations']          [h5_start:h5_start+location.shape[0]] = location
    f['contribution_scores'][h5_start:h5_start+location.shape[0]] = results

    h5_start = h5_start+location.shape[0]

    '''
    batch_size, n_tokens, length = sequence.shape
    mutated = mutagenizer(sequence)

    forward = flank_builder(mutated).contiguous()
    revcomp = flank_builder(mutated.flip(dims=(1,2))).contiguous()

    result = my_model(forward.cuda()).div(2.) + my_model(revcomp.cuda()).div(2.)

    result = result.unflatten(0,(batch_size, n_tokens, seq_len)).mean(dim=2)

    for (chrom_idx, start, end, strand), position_activity in zip(location, result):
        f[ fasta_data.idx2key[chrom_idx] ][start+seq_len-1] = position_activity.cpu().half().numpy()
'''
    
f.close()

  0%|          | 100/4428412 [05:10<3814:55:40,  3.10s/it]

CPU times: user 3min 53s, sys: 58.2 s, total: 4min 51s
Wall time: 5min 10s


In [66]:
f.close()

In [69]:
f = h5py.File('test_write.hdf5','r')

In [75]:
f['contribution_scores'][h5_start-28:h5_start+1]

array([[[[ 9.2163e-03,  2.3544e-02,  3.7781e-02],
         [ 6.9084e-03,  2.5909e-02,  2.5467e-02],
         [ 7.3318e-03,  1.0391e-02,  5.0240e-03],
         ...,
         [ 1.8951e-02,  1.2131e-02,  2.8015e-02],
         [ 3.0533e-02,  1.6281e-02,  9.4528e-03],
         [ 4.6082e-02,  2.9037e-02,  7.5531e-03]],

        [[ 3.9215e-03, -4.0817e-03, -2.2888e-03],
         [-6.9199e-03, -1.8311e-02, -2.0020e-02],
         [-1.2970e-02, -3.8891e-03, -1.9150e-03],
         ...,
         [ 5.4169e-02,  3.3997e-02,  3.1189e-02],
         [ 4.0894e-02,  3.4424e-02,  1.3039e-02],
         [ 3.9062e-02,  2.1271e-02,  5.5199e-03]],

        [[-1.2291e-02, -1.6174e-02, -2.6627e-02],
         [-6.6719e-03,  7.6256e-03,  4.3144e-03],
         [ 1.5707e-03,  4.5738e-03,  8.9722e-03],
         ...,
         [-1.3130e-02,  6.6757e-03, -1.2085e-02],
         [-9.5215e-02, -8.2581e-02, -3.4180e-02],
         [-1.5967e-01, -8.0994e-02, -5.9937e-02]],

        [[-8.4972e-04, -3.2997e-03, -8.8806e-03],
  

In [76]:
f['positions'][h5_start-28:h5_start+1]

array([[    0, 68600, 68800,     1],
       [    0, 68650, 68850,     1],
       [    0, 68700, 68900,     1],
       [    0, 68750, 68950,     1],
       [    0, 68800, 69000,     1],
       [    0, 68850, 69050,     1],
       [    0, 68900, 69100,     1],
       [    0, 68950, 69150,     1],
       [    0, 69000, 69200,     1],
       [    0, 69050, 69250,     1],
       [    0, 69100, 69300,     1],
       [    0, 69150, 69350,     1],
       [    0, 69200, 69400,     1],
       [    0, 69250, 69450,     1],
       [    0, 69300, 69500,     1],
       [    0, 69350, 69550,     1],
       [    0, 69400, 69600,     1],
       [    0, 69450, 69650,     1],
       [    0, 69500, 69700,     1],
       [    0, 69550, 69750,     1],
       [    0, 69600, 69800,     1],
       [    0, 69650, 69850,     1],
       [    0, 69700, 69900,     1],
       [    0, 69750, 69950,     1],
       [    0, 69800, 70000,     1],
       [    0, 69850, 70050,     1],
       [    0, 69900, 70100,     1],
 

In [72]:
h5_start

1400

In [56]:
''.join([ ['A','C','G','T'][pos] for pos in sequence[-1].argmax(dim=0) ])

'AACCTGCCCCACAGCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTTTTTGTGGGAGACTATTCCTCCCATCTGCAACAGCTGCCCCTGCTGACTGCCCTTCTCTCCTCCCTCTCATCCCAGAGAAACAGGTCAGCTGGGAGCTTCTGCCCCCACTGCCTAGGGACCAACAGGGGCAGGAGGCAGTCACTGACCCCGAGACGTTTGCATCCTGCACAGCTAGAGATCCTTTATTAAAAGCACACT'

In [59]:
spot_check = 'ACCTGCCCCACAGCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTT'
spot_check

'ACCTGCCCCACAGCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTT'

In [58]:
''.join([ ['A','C','G','T'][pos] for pos in sequence[-1].argmax(dim=0) ])[1:201] == spot_check

True

In [60]:
print(spot_check)
print(''.join([ ['A','C','G','T'][pos] for pos in sequence[-1].argmax(dim=0) ]))

ACCTGCCCCACAGCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTT
AACCTGCCCCACAGCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTTTTTGTGGGAGACTATTCCTCCCATCTGCAACAGCTGCCCCTGCTGACTGCCCTTCTCTCCTCCCTCTCATCCCAGAGAAACAGGTCAGCTGGGAGCTTCTGCCCCCACTGCCTAGGGACCAACAGGGGCAGGAGGCAGTCACTGACCCCGAGACGTTTGCATCCTGCACAGCTAGAGATCCTTTATTAAAAGCACACT


In [43]:
f = h5py.File('test_write.hdf5','r')

In [47]:
f['chr1'].set_fill_value = np.nan

In [52]:
f['chr1'][20000:20000+200]

array([[[ 1.041   ,  1.652   ,  1.066   ],
        [ 0.9307  ,  1.658   ,  1.003   ],
        [ 1.042   ,  1.621   ,  1.094   ],
        [ 1.033   ,  1.928   ,  1.1875  ]],

       [[ 1.847   ,  1.809   ,  1.184   ],
        [ 0.9243  ,  1.65    ,  0.9995  ],
        [ 1.093   ,  1.468   ,  0.992   ],
        [ 1.027   ,  1.159   ,  1.001   ]],

       [[ 0.9385  ,  1.434   ,  0.778   ],
        [ 0.991   ,  1.672   ,  0.951   ],
        [ 1.063   ,  1.645   ,  1.122   ],
        [ 0.9194  ,  1.644   ,  0.997   ]],

       ...,

       [[-0.03079 ,  0.3694  ,  0.553   ],
        [-0.02925 ,  0.3591  ,  0.593   ],
        [-0.01709 ,  0.391   ,  0.619   ],
        [-0.05405 ,  0.3223  ,  0.565   ]],

       [[-0.03995 ,  0.345   ,  0.5503  ],
        [-0.01889 ,  0.3901  ,  0.6196  ],
        [-0.07196 ,  0.316   ,  0.536   ],
        [-0.0373  ,  0.3628  ,  0.576   ]],

       [[-0.03223 ,  0.357   ,  0.5757  ],
        [-0.006172,  0.4006  ,  0.632   ],
        [-0.033   ,  0.366   , 

In [53]:
f.close()

In [40]:
''.join([ ['A','C','G','T'][pos] for pos in sequence[-1].argmax(dim=0) ])[1:201] == spot_check

True

In [13]:
del my_model
import gc
torch.cuda.empty_cache()
gc.collect()

48

In [26]:
results_holder['chr1'].shape[0] / 10

24895642.2

In [22]:
hold = torch.stack(
    [torch.tensor(fasta_dict.fasta['chr1'][:,20000:20399], dtype=torch.float), torch.tensor(fasta_dict.fasta['chr1'][:,20001:20400], dtype=torch.float)],
    dim=0
)
hold

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 1.],
         [0., 0., 1.,  ..., 1., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 1.,  ..., 1., 1., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.]]])

In [23]:
mutagenizer(hold).shape

torch.Size([1600, 4, 200])

In [25]:
trash_3 = np.array([ "".join([['A','C','G','T'][token] for token in seq.argmax(dim=0)]) for seq in mutagenizer(hold) ])
_ = [ print(x) for x in trash_3 ]


CCTGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCA
CTGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAG
TGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAGT
GGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAGTG
GTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCA

In [171]:
hold = torch.tensor(fasta_dict.fasta['chr1'][:,20000:20399], dtype=torch.float)

clear= torch.ones_like(hold)
clear[:,199] = 0

hold = hold.mul(clear).unsqueeze(0).expand(4,-1,-1)

mut = torch.zeros_like(hold)
mut[torch.arange(4), torch.arange(4), 199] = 1

hold = hold + mut

In [172]:
hold[:,:,199]

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [144]:
hold.shape

torch.Size([4, 4, 399])

In [175]:
trash_3 = np.array([ "".join([['A','C','G','T'][token] for token in seq.argmax(dim=0)]) for seq in windower( hold ) ])

In [178]:
trash_3.reshape(4,200)

array([['CCTGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCA',
        'CTGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAG',
        'TGGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAGT',
        'GGTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCAGCACTGCTCGAAATGTACAGCATTTCTCTTTGTAACAGGATTATTAGCCTGCAGTG',
        'GTGCTCCCACAAAGGAGAAGGGCTGATCACTCAAAGTTGCGAACACCAAGCTCAACAATGAGCCCTGGAAAATTTCTGGAATGGATTATTAAACAGAGAGTCTGTAAGCACTTAGAAAAGGCCGCGGTGAGTCCCAGGGGCCA

In [ ]:
windower

In [86]:
fasta_dict

In [82]:
result

tensor([[0.6092, 0.6311, 0.7916],
        [0.5838, 0.5964, 0.7459],
        [0.5771, 0.5771, 0.7246],
        ...,
        [0.5771, 0.5771, 0.7246],
        [0.5838, 0.5964, 0.7459],
        [0.6092, 0.6311, 0.7916]], device='cuda:0')

In [78]:
inputs[:,:,200:400]

tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0

In [73]:
mutated.shape

torch.Size([8000, 4, 200])

In [70]:
x[1].shape

torch.Size([10, 4, 200])

In [11]:
class MutagenesisDataset(Dataset):
    
    def __init__(self, 
                 fasta_obj, window_size, step_size, 
                 reverse_complements=True,
                 left_flank='', right_flank='', 
                 alphabet=constants.STANDARD_NT,
                 complement_dict=constants.DNA_COMPLEMENTS,
                 pad_final=False):
        
        super().__init__()
        
        assert step_size <= window_size, "Gaps will form if step_size > window_size"
        
        self.fasta = fasta_obj
        self.window_size = window_size
        self.step_size = step_size
        
        self.reverse_complements = reverse_complements
        
        self.left_flank = left_flank
        self.right_flank= right_flank
        self.alphabet = alphabet
        self.complement_dict = complement_dict
        self.complement_matrix = self.parse_complements()
        
        self.pad_final  = pad_final
        
        self.n_keys = len(self.fasta.keys())
        self.key_lens =  { k: self.fasta[k].shape[-1] for k in self.fasta.keys() }
        self.key_n_windows = self.count_windows()
        self.key_rolling_n = np.cumsum([ self.key_n_windows[k] for k in self.fasta.keys() ])
        
        self.key2idx  = { k:i for i,k in enumerate(self.fasta.keys()) }
        self.idx2key  = list(self.fasta.keys())
        
        self.n_unstranded_windows = sum( self.key_n_windows.values() )
                    
    def count_windows(self):
        
        key_n_windows = {}
        
        for k, v in self.key_lens.items():
            
            if v >= self.window_size:
                n = 1
                n += (v - self.window_size) // self.step_size
                if self.pad_final:
                    n += 1 if (v - self.window_size) % self.step_size > 0 else 0
                
            else:
                n = 0
                
            key_n_windows[k] = n
        
        return key_n_windows
        
    def add_flanks(self, x):
        
        pieces = []
        
        pieces.append( self.left_flank )
            
        pieces.append( x )
        
        pieces.append( self.right_flank )
            
        return "".join(pieces)
    
    def get_fasta_coords(self, idx):
        
        k_id = self.n_keys - sum(self.key_rolling_n > idx)
        n_past = 0 if k_id == 0 else self.key_rolling_n[k_id-1]
        window_idx = idx - n_past
        
        k = self.idx2key[k_id]
        start = window_idx * self.step_size
        end   = min(start + self.window_size, self.key_lens[k])
        start = end - self.window_size
        
        return {'key': k, 'start': start, 'end': end}

    def parse_complements(self):
        
        comp_mat = np.zeros( (len(self.alphabet),len(self.alphabet)) )
        
        for i in range(len(self.alphabet)):
            target_index = self.alphabet.index( self.complement_dict[ self.alphabet[i] ] )
            comp_mat[target_index,i] = 1
        return comp_mat
    
    def __len__(self):
        
        strands = 2 if self.reverse_complements else 1
        
        return self.n_unstranded_windows * strands
    
    def __getitem__(self, idx):
        
        if self.reverse_complements:
            strand = 1 if idx % 2 == 0 else -1
            u_idx = idx // 2
        
        fasta_loc = self.get_fasta_coords(u_idx)
        k, start, end = [fasta_loc[x] for x in ['key', 'start', 'end']]
        
        fasta_seq = self.fasta[k][:,start:end].astype(np.float32)
        fasta_seq = fasta_seq if strand == 1 else np.flip( self.complement_matrix @ fasta_seq, axis=-1)
        fasta_seq = torch.tensor(fasta_seq.copy())
        
        loc_tensor= torch.tensor([self.key2idx[k], start, end, strand])
        
        return loc_tensor, fasta_seq


{'chr1': array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 'chr2': array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 'chr3': array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 'chr4': array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 'chr5': array([[False, False, False, ..., False